# -*- coding: utf-8 -*-
"""ROC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VOBgm4qsghrQnyI71ii7mCZ_i7uxyjhC
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.markers import MarkerStyle
from matplotlib import patches
p = [-0.5,0]
p_real = [x.real for x in p]
p_imag = [x.imag for x in p]
z = [-1j,1j]
z_real = [x.real for x in z]
z_imag = [x.imag for x in z]

x = np.linspace(-2,2,100)
ax = plt.subplot(111)
# Add unit circle and zero axes    
unit_cir = patches.Circle((0,0), radius=1, fill=False,color='black', ls='dashed')
ax.add_patch(unit_cir)

z1 = np.sqrt(16-x**2)
z2 = -np.sqrt(16-x**2)
plt.fill_between(x, z1, z2, color='#539ecd')

# Add circle passing through max abs(poles) and zero axes    
req_cir = patches.Circle((0,0), radius=np.max(np.abs(p))
			, fill=True,color='white',ls='solid')
ax.add_patch(req_cir)
boundary = patches.Circle((0,0), radius=np.max(np.abs(p))
			, fill=False,color='black',ls='solid')
ax.add_patch(boundary)

plt.plot(z_real,z_imag,'o',markersize=7,color='green')
plt.plot(p_real,p_imag,'x',color='red',markersize=7)
plt.text(0,0.1,"z=0")
plt.text(0.2,0.7,"|z|>0.5")
plt.text(-0.6,1.0,"|z|=1")
plt.text(0,1.1,'1j')
plt.text(0,-1.12,'-1j')
plt.text(-0.6,0.1,'-0.5j')
plt.title('H(z) in z plane')
plt.xlabel('real')
plt.ylabel('Imaginary')
plt.grid()# minor
plt.axis('scaled')
plt.axis([-1.5,1.5,-1.5,1.5])


#else
#plt.show()

